# Generated by Django 5.1.4 on 2025-01-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Corretagem",
            new_name="Corretagem_user",
        ),
    ]
