# Generated by Django 5.1.4 on 2025-01-01 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_rename_corretagem_corretagem_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taxas_user",
            fields=[
                ("taxas_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "taxas_acoes_brasileiras",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "taxas_indice_futuro",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "taxas_dolar_futuro",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "taxa_acoes_brasileiras",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "taxa_indice_futuro",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "taxa_dolar_futuro",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Corretagem_user",
        ),
    ]
