# Generated by Django 5.1.4 on 2025-01-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_taxas_user_delete_corretagem_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taxas_user",
            old_name="taxa_acoes_brasileiras",
            new_name="corretagem_acoes_brasileiras",
        ),
        migrations.RenameField(
            model_name="taxas_user",
            old_name="taxa_dolar_futuro",
            new_name="corretagem_dolar_futuro",
        ),
        migrations.RenameField(
            model_name="taxas_user",
            old_name="taxa_indice_futuro",
            new_name="corretagem_indice_futuro",
        ),
    ]
