# Generated by Django 5.1.4 on 2025-01-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0004_rename_taxa_acoes_brasileiras_taxas_user_corretagem_acoes_brasileiras_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxas_user",
            name="taxas_acoes_brasileiras",
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
