# Generated by Django 5.1.4 on 2025-05-29 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corretora', models.CharField(blank=True, max_length=255, null=True, verbose_name='Corretora')),
                ('ativo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ativo')),
                ('lado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lado')),
                ('ultima_atualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Atualização')),
                ('qtd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade')),
                ('preco_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Médio')),
                ('qtd_executada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qtd. Executada')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total')),
                ('total_executado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Executado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
