# Generated by Django 5.1.4 on 2025-05-30 10:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operacao',
            options={'ordering': ['-data_operacao', '-horario_operacao'], 'verbose_name': 'Operação de Trade', 'verbose_name_plural': 'Operações de Trade'},
        ),
        migrations.RenameField(
            model_name='operacao',
            old_name='qtd',
            new_name='quantidade',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='corretora',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='preco_medio',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='qtd_executada',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='ultima_atualizacao',
        ),
        migrations.AddField(
            model_name='operacao',
            name='anotacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Anotações'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='conta_selecionada',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Conta Selecionada'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='corretagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Corretagem'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='corretora_info_adicional',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Corretora Info Adicional'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='data_atualizacao_registro',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização do Registro'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='data_criacao_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 30, 10, 32, 58, 764159), verbose_name='Data de Criação do Registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operacao',
            name='data_operacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Operação'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='horario_operacao',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário da Operação'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='preco_operacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço da Operação'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='lado',
            field=models.CharField(blank=True, choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda')], max_length=6, null=True, verbose_name='Lado'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total (Outra Fonte)'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='total_executado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Executado (Outra Fonte)'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
