# Generated by Django 5.1.4 on 2025-05-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_alter_operacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='lado',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda')], default='COMPRA', max_length=6, verbose_name='Lado'),
            preserve_default=False,
        ),
    ]
